const lessonTitle = "涌泉跃鲤";

const lessonData = [
    // ===== 第1段 =====
    ["汉", "hàn", "Han Dynasty", "Dinasti Han"],
    ["姜诗", "jiāng shī", "Jiang Shi", "Jiang Shi"],
    ["，", "", "", ""],
    ["事", "shì", "served", "melayani"],
    ["母", "mǔ", "mother", "ibu"],
    ["至", "zhì", "extremely", "sangat"],
    ["孝", "xiào", "filial", "berbakti"],
    ["。", "", "", ""],
    ["妻", "qī", "Wife", "Isteri"],
    ["庞氏", "páng shì", "Pang Shi", "Pang Shi"],
    ["，", "", "", ""],
    ["奉", "fèng", "served", "melayani"],
    ["姑", "gū", "mother-in-law", "mentua"],
    ["尤", "yóu", "especially", "lebih"],
    ["谨", "jǐn", "respectfully", "dengan penuh hormat"],
    ["。", "", "", ""],
    ["母", "mǔ", "Mother", "Ibu"],
    ["性好", "xìng hǎo", "liked", "suka"],
    ["饮", "yǐn", "drink", "minum"],
    ["江水", "jiāng shuǐ", "river water", "air sungai"],
    ["，", "", "", ""],
    ["去舍", "qù shè", "distance from home", "jarak dari rumah"],
    ["六七里", "liù qī lǐ", "six or seven li", "enam tujuh li"],
    ["，", "", "", ""],
    ["妻", "qī", "wife", "isteri"],
    ["出汲", "chū jí", "went out to draw water", "keluar mengambil air"],
    ["以", "yǐ", "to", "untuk"],
    ["奉之", "fèng zhī", "serve her", "melayaninya"],
    ["。", "", "", ""],
    ["又", "yòu", "Also", "Juga"],
    ["嗜", "shì", "liked", "suka"],
    ["鱼脍", "yú kuài", "fish dish", "hidangan ikan"],
    ["，", "", "", ""],
    ["夫妇", "fū fù", "husband and wife", "suami isteri"],
    ["常", "cháng", "often", "sering"],
    ["作", "zuò", "made", "membuat"],
    ["。", "", "", ""],
    ["又", "yòu", "Also", "Juga"],
    ["不能", "bù néng", "could not", "tidak boleh"],
    ["独食", "dú shí", "eat alone", "makan seorang diri"],
    ["，", "", "", ""],
    ["召", "zhào", "invited", "menjemput"],
    ["邻母", "lín mǔ", "neighbor mother", "jiran perempuan"],
    ["共食", "gòng shí", "to eat together", "makan bersama"],
    ["。", "", "", ""],
    ["舍侧", "shè cè", "Beside the house", "Di sisi rumah"],
    ["忽有", "hū yǒu", "suddenly there was", "tiba-tiba ada"],
    ["涌泉", "yǒng quán", "spring gushing forth", "air pancut"],
    ["，", "", "", ""],
    ["味", "wèi", "taste", "rasa"],
    ["如", "rú", "like", "seperti"],
    ["江水", "jiāng shuǐ", "river water", "air sungai"],
    ["，", "", "", ""],
    ["日", "rì", "daily", "setiap hari"],
    ["跃", "yuè", "jumped", "melompat"],
    ["双鲤", "shuāng lǐ", "two carp", "dua ekor ikan"],
    ["，", "", "", ""],
    ["取", "qǔ", "took", "mengambil"],
    ["以", "yǐ", "to", "untuk"],
    ["供", "gòng", "offer", "menghidangkan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["《", "", "", ""],
    ["二十四孝", "èr shí sì xiào", "The Twenty-Four Filial Exemplars", "Dua Puluh Empat Contoh Kebaktian"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
