const lessonTitle = "涌泉跃鲤";

const lessonData = [
    // ===== 文言文 =====
    ["汉", "hàn", "Han Dynasty", "Dinasti Han", "东汉"],
    ["姜诗", "jiāng shī", "Jiang Shi", "Jiang Shi", "姜诗"],
    ["，", "", "", "", ""],
    ["事", "shì", "served", "melayani", "侍奉"],
    ["母", "mǔ", "mother", "ibu", "母亲"],
    ["至", "zhì", "extremely", "sangat", "非常"],
    ["孝", "xiào", "filial", "berbakti", "孝顺"],
    ["。", "", "", "", ""],
    ["妻", "qī", "Wife", "Isteri", "妻子"],
    ["庞氏", "páng shì", "Pang Shi", "Pang Shi", "庞氏"],
    ["，", "", "", "", ""],
    ["奉", "fèng", "served", "melayani", "侍奉"],
    ["姑", "gū", "mother-in-law", "mentua", "婆婆"],
    ["尤", "yóu", "especially", "lebih", "更加"],
    ["谨", "jǐn", "respectfully", "dengan penuh hormat", "恭敬谨慎"],
    ["。", "", "", "", ""],
    ["母", "mǔ", "Mother", "Ibu", "母亲"],
    ["性好", "xìng hǎo", "liked", "suka", "喜欢"],
    ["饮", "yǐn", "drink", "minum", "喝"],
    ["江水", "jiāng shuǐ", "river water", "air sungai", "江水"],
    ["，", "", "", "", ""],
    ["去舍", "qù shè", "distance from home", "jarak dari rumah", "距离家"],
    ["六七里", "liù qī lǐ", "six or seven li", "enam tujuh li", "六七里"],
    ["，", "", "", "", ""],
    ["妻", "qī", "wife", "isteri", "妻子"],
    ["出汲", "chū jí", "went out to draw water", "keluar mengambil air", "出去取水"],
    ["以", "yǐ", "to", "untuk", "用来"],
    ["奉之", "fèng zhī", "serve her", "melayaninya", "侍奉她"],
    ["。", "", "", "", ""],
    ["又", "yòu", "Also", "Juga", "又"],
    ["嗜", "shì", "liked", "suka", "喜欢"],
    ["鱼脍", "yú kuài", "fish dish", "hidangan ikan", "鱼做的菜"],
    ["，", "", "", "", ""],
    ["夫妇", "fū fù", "husband and wife", "suami isteri", "夫妻俩"],
    ["常", "cháng", "often", "sering", "常常"],
    ["作", "zuò", "made", "membuat", "做"],
    ["。", "", "", "", ""],
    ["又", "yòu", "Also", "Juga", "又"],
    ["不能", "bù néng", "could not", "tidak boleh", "不"],
    ["独食", "dú shí", "eat alone", "makan seorang diri", "独自吃"],
    ["，", "", "", "", ""],
    ["召", "zhào", "invited", "menjemput", "邀请"],
    ["邻母", "lín mǔ", "neighbor mother", "jiran perempuan", "邻居"],
    ["共食", "gòng shí", "to eat together", "makan bersama", "一起吃"],
    ["。", "", "", "", ""],
    ["舍侧", "shè cè", "Beside the house", "Di sisi rumah", "房子旁边"],
    ["忽有", "hū yǒu", "suddenly there was", "tiba-tiba ada", "忽然出现"],
    ["涌泉", "yǒng quán", "spring gushing forth", "air pancut", "涌出的泉水"],
    ["，", "", "", "", ""],
    ["味", "wèi", "taste", "rasa", "味道"],
    ["如", "rú", "like", "seperti", "像"],
    ["江水", "jiāng shuǐ", "river water", "air sungai", "江水"],
    ["，", "", "", "", ""],
    ["日", "rì", "daily", "setiap hari", "每天"],
    ["跃", "yuè", "jumped", "melompat", "跃出"],
    ["双鲤", "shuāng lǐ", "two carp", "dua ekor ikan", "两条鲤鱼"],
    ["，", "", "", "", ""],
    ["取", "qǔ", "took", "mengambil", "取来"],
    ["以", "yǐ", "to", "untuk", "用来"],
    ["供", "gòng", "offer", "menghidangkan", "供奉"],
    ["。", "", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", "", ""],
    ["《", "", "", "", ""],
    ["二十四孝", "èr shí sì xiào", "The Twenty-Four Filial Exemplars", "Dua Puluh Empat Contoh Kebaktian", "二十四孝"],
    ["》", "", "", "", ""],
    ["，", "", "", "", ""],
    ["有", "yǒu", "with", "ada", "有"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai", "改动"],
    ["）", "", "", "", ""]
];
